name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22.0.1'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Verify JAR exists
        run: |
          ls -la target/
          JAR_FILE=$(ls target/*.jar)
          echo "JAR file: $JAR_FILE"
          if [ ! -f "$JAR_FILE" ]; then
            echo "JAR file not found!"
            exit 1
          fi

      - name: Run application and test
        run: |
          # Запускаем приложение в фоне
          JAR_FILE=$(ls target/*.jar)
          java -jar $JAR_FILE &
          
          # Ждём запуска (адаптируйте под ваше приложение)
          echo "Waiting for app to start..."
          sleep 15
          
          # Проверяем доступность
          curl -f http://localhost:8080/actuator/health || exit 1
          
          # Запускаем тесты
          mvn test