jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B clean package
      - name: Run tests
        run: |
          mvn test -Dspring.profiles.active=test
          # Дополнительная проверка
          JAR_FILE=target/filmorate-*.jar
          java -jar $JAR_FILE --spring.profiles.active=test &
          APP_PID=$!
          sleep 15
          curl -f http://localhost:8080/actuator/health || exit 1
          kill $APP_PID